name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  go-explorer-app-deployment-pipeline:
    runs-on: ubuntu-20.04
    env:
      COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
      PORT: 5000
      GOLANG_VERSIONS: 1.17;1.16;1.18-rc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: build GO image
        run: |
          docker build . -f ./backend/src/docker/Dockerfile.go117 -t golang:1.17
          docker build . -f ./backend/src/docker/Dockerfile.go118 -t golang:1.18-rc
      - name: npm install
        run: |
          npm install --prefix backend/
          npm install --prefix frontend/
      - name: code quality - formatting check
        run: |
          npm run --prefix backend/ check:format
          npm run --prefix frontend/ check:format
      - name: code quality - linting
        run: |
          npm run --prefix backend/ lint
          npm run --prefix frontend/ lint
      - name: build
        run: |
          npm run --prefix backend/ build
          npm run --prefix frontend/ build
      - name: backend - unit/integration tests
        run: |
          npm run --prefix backend/ test
      - name: start backend and frontend
        run: |
          npm run --prefix backend/ start:test &
          npm run --prefix frontend/ start:dev &
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run --prefix frontend/ test:e2e
          wait-on: http://localhost:3000
          project: ./frontend
          config: video=false